experimental_monorepo_root = true

[env]
MISE_EXPERIMENTAL = 1

[tools]
biome = "latest"
node = "24.13.0"
pnpm = "latest"

[tasks.lint]
description = "Run biome lint"
run = "biome lint ."

[tasks.deploy]
description = "deploy the subject"
run = [
  "cd live/",
  "git pull",
  "docker compose build",
  "docker compose down",
  "docker compose up -d",
]

